### ISSUE TITLE
How long does it take for repo maintainers to review PRs?

### ISSUE THREAD

**Issue by d-sfounis** [cardano-foundation/cardano-token-registry#1114]
I didn't want to sound uncourteous, just looking to get an estimate for how long it usually takes

**Comment by d-sfounis** [comment]
7 days and counting, so far.

**Comment by ggcaponetto** [comment]
Wondering the same...

**Comment by d-sfounis** [comment]
> Wondering the same...

I've found out that if your PR doesn't pass validation, it's not gonna go through and/or force closed. Make sure yours does by running `token-metadata-crator validate` on your local machine before pushing a PR

**Comment by ggcaponetto** [comment]
@d-sfounis thanks you for that info. Mine is passing the validation. I think I have no option than wait for a repo maintainer to trigger my actions because I am a first time contributor.

**Comment by cleanerm5** [comment]
Hi @d-sfounis 

first of all sorry for getting back to you that late and thanks for bringing that up. The delay at the beginning of the year was eventually caused due to the handover and my onboarding.

At the moment the review process is done manually by cf-admin or myself and we are working on improving this process which is pragmatic but for non tech-people and sometimes even for tech-people a bit cumbersome.

But for now I am doing the reviews at least once a day (on workdays) and whether do the merging or comment on failed validations.

Sincerely

**Comment by cleanerm5** [comment]
I will close this issue soon if there are no other related comments, questions etc. from your side. Otherwise, let me know.

**Comment by d-sfounis** [comment]
> I will close this issue soon if there are no other related comments, questions etc. from your side. Otherwise, let me know.

Since you're here, let's close this :-)
You got this!
