### ISSUE TITLE
add information/standard to add metadata for NFT projects

### ISSUE THREAD

**Issue by ashisherc** [cardano-foundation/cardano-token-registry#24]
The current specification allows submitting metadata for tokens ie. policyId+assetName. We should also have a specification for adding metadata for the NFT project, specifically adding metadata for the policy itself. Having metadata for an NFT project with only policyId and no AssetName (still valid) may not be the best choice as it can easily clash with actual tokens with no AssetName.

The creator can still add metadata for the individual NFT tokens via the current token specification.

**Comment by ashisherc** [comment]
Having this at the earliest will avoid submissions like this one https://github.com/cardano-foundation/cardano-token-registry/pull/23

**Comment by crptmppt** [comment]
@ashisherc - unsure if there is a specific concern here, thanks for flagging as needed.
You might be interested in the conversation taking place as a tentative [CIP for NFT metadata standard ](https://github.com/cardano-foundation/CIPs/pull/85) - this will be discussed at the upcoming Editors meeting next week.

**Comment by ftpmorph** [comment]
> unsure if there is a specific concern here

If the policy of the registry is that every submission must be linked to a specific token, this is absolutely a concern for NFTs as by definition each NFT should be its own unique token and it would simply be impractical to require NFT creators to add a separate entry for every single token they mint... that's a lot of unnecessary work for both the creators and yourselves.

To accommodate NFTs it is as simple as allowing submissions that link to a policy ID rather than a specific token under it if the project in question is an NFT. @ashisherc raises a valid concern here because if these allowances are not made, the registry is effectively useless for NFT creators.

I looked through the discussion on an NFT metadata standard, but this seems distinct from inclusion in the registry. It seems to me the inclusion of NFTs in this registry really is as simple as allowing policy IDs to be submitted rather than specific tokens.

**Comment by crptmppt** [comment]
@ftpmorph keep in mind that the Foundation runs AN instance of a registry, and that others will likely come up and build supersets. Accordingly, the Foundation has for the time being taken the position of enforcing more restrictive entry criterias: The Cardano Token Registry was initially intent to support only coin-like tokens. 
I expect the Foundation's Cardano Token Registry to grow beyond its initial scope - but in its current iteration it is a very simple (limited) setup - Linking a policyID sounds like it would open the door to minting considerations that do not exist with single token registration.. I invite you to push the conversation towards a formal ask, likely best through the CIP framework, to open up and share visibility as needed if feasible!

**Comment by Godspeed-exe** [comment]
Closing because of old age. Feel free to open new discussions if still revelant.
