### ISSUE TITLE
API Metadata not working token not showing up as in registry on some websites even after being merged to the Token Registry 

### ISSUE THREAD

**Issue by GavinKarlsson** [cardano-foundation/cardano-token-registry#2763]
The token metadata was merged last week:
![image](https://media.discordapp.net/attachments/907569785611636757/1085553926557929514/image.png)
Pull request https://github.com/cardano-foundation/cardano-token-registry/pull/2749

However the metadata and api is not working on some sites:
https://api.metadata.staging.cf-deployments.org/v2/subjects/bf9354cba4ee83c5de05c72830c6430967a26a1656b06293541d23e154414e47

https://cardanoassets.com/asset1p54t5653v8xslldtu9v3uh4sfwprkj046k3ujm
![image](https://user-images.githubusercontent.com/100855173/225699557-52f6b9de-2d68-4ef9-a1ef-1ee28dc43f8b.png)

Please advise.

**Comment by cleanerm5** [comment]
Hi @GavinKarlsson 

thanks for pointing this out. I found the issue...

The cache serving the data to the API indexes the subject case sensitive and the "etl" process (bit too much to call it that way) does not "to_lower" the content of the field while processing the file whereas the db lookup is then case sensitive. If you have a closer look at the subject in your PR you figure out there is a capital "E" at the end just before the last byte.

So if you change the query path to the following it works:
https://api.metadata.staging.cf-deployments.org/v2/subjects/bf9354cba4ee83c5de05c72830c6430967a26a1656b06293541d23e154414E47

I correct it a bit later and let you know so that it also works in the Cexplorer again for your and any other assets that might suffer from this bug.

**Comment by cleanerm5** [comment]
Hey @GavinKarlsson 

I have to partially correct my reply: Because of the signing scheme the approach to fix it above will not work.

The signatures for the different fields are created from the subject itself concatenated with the field name, value and sequenceNumber. If the downstream processing "lower-cases" your subject string the signature will be incorrect. Technically, even if I make the search case-insensitive it could lead to ambiguous results (e.g. if you register multiple metadata files where you "alter" the capitalization of single chars)

Best thing to do at the moment would be to file a new PR with a lower-case subject string.

Kind regards and sorry for the inconvenience

**Comment by ScottBlaney** [comment]
Sorry for the inconvenience everyone. Thank you @cleanerm5 for your assistance in this matter. 
I have corrected my mistake and made a new PR https://github.com/cardano-foundation/cardano-token-registry/pull/2765

**Comment by ScottBlaney** [comment]
Sorry for the inconvenience. Thank you @cleanerm5 for your assistance with this matter. I have fixed the file and made a new PR https://github.com/cardano-foundation/cardano-token-registry/pull/2766

**Comment by cleanerm5** [comment]
Looks good now according to the API and also CExplorer. Closing this issue
