### ISSUE TITLE
Add image for token logo

### ISSUE THREAD

**Issue by LexyCoinADA** [cardano-foundation/cardano-token-registry#3571]
Good day, How do we add an image for our token logo?

**Comment by Kartiiyer12** [comment]
Hi @LexyCoinADA There has to be entry in the Cardano registry so that the DEX and other platforms can get the token registry. Create PR for your asset by adding information about the asset. Please refer to the wiki below,
https://github.com/cardano-foundation/cardano-token-registry/wiki

Also, refer to the docs below to understand about the token registration. 
https://developers.cardano.org/docs/native-tokens/cardano-token-registry/

**Comment by LexyCoinADA** [comment]
Thank you. We'll take a look into this.
