### ISSUE TITLE
Pls help me for update name of token

### ISSUE THREAD

**Issue by billpi1** [cardano-foundation/cardano-token-registry#3966]
Here is original merge:
https://github.com/billpi1/cardano-token-registry/blob/4a9e3fb67f0484915ddf6924b298ab8c62ea59d2/mappings/4f2a93e7e89d2db75ade14859a0002a8debb25b877145099c32b6ed455454641.json

I  can not delete that file and new file can not be upload as old same name file exists already

Pls guide me to fix this issue . It took long time from me :(

**Comment by Kartiiyer12** [comment]
Hi @billpi1 The file name remains the same, the sequence number increments in the file. Please check out the wiki below for more detailed explanation - 
https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

- If you have draft file from the first submission, that had not been signed, you can update the values and increment the sequence number, sign and then submit that file. 
- Otherwise, you can create new draft file, use updated data and increment the sequence number. 
The wiki explains both the process.

**Comment by Godspeed-exe** [comment]
@billpi1 

On your repo you should be able to make any changes to these files. Once you updated your repo you can create a new pull request on this repo.

Below is a guide on how you can update. Take into account that you have to (i) increment the sequenceNumber value, (ii) re-sign the updated value. 
https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

**Comment by billpi1** [comment]
Please. Check file . It still failed;
https://github.com/cardano-foundation/cardano-token-registry/pull/3964
