### ISSUE TITLE
Access to cardano-token-registry/mappings is needed to upload the SPCOL Token registration file.

### ISSUE THREAD

**Issue by SPOOLCOLOGNE** [cardano-foundation/cardano-token-registry#4295]
Please, I need access to upload my SPCOL Token registration file .json. I receive the following message: Uploads are disabled. File uploads require push access to this repository.
[5695e476953cd3f9a7f77c10f879112b070e8ec65cc171d29cef8ca95350434f4c.json](https://github.com/cardano-foundation/cardano-token-registry/files/14730969/5695e476953cd3f9a7f77c10f879112b070e8ec65cc171d29cef8ca95350434f4c.json)

**Comment by VladislavKudrin** [comment]
Hi @SPOOLCOLOGNE,

you do not need access to the main repository, since you are operating on your fork and then submitting the pull request to the master branch. You can read more here: [How to submit an entry to the registry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-submit-an-entry-to-the-registry)

The first step is forking the repo. 

Let me know if you have any questions!

**Comment by SPOOLCOLOGNE** [comment]
Hello Vladislav Kudrin,

Thank you for your quick response, now I am receiving this message:

git clone git@github.com:SPOOLCOLOGNE/cardano-token-registry
Cloning into 'cardano-token-registry'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

TKS

**Comment by VladislavKudrin** [comment]
I do not see the fork in your profile. Go to https://github.com/cardano-foundation/cardano-token-registry and fork it 
<img width="610" alt="1" src="https://github.com/cardano-foundation/cardano-token-registry/assets/17981725/4dc1d48a-d4ee-46f0-8b11-7cdae85edd6d"> 

Then you can go to your fork and upload the file into the mappings folder. All this can be done without terminal use, just with github UI.

**Comment by SPOOLCOLOGNE** [comment]
Thank you very much, it has worked.

**Comment by SPOOLCOLOGNE** [comment]
Thank you very much, it has worked.
